spring.application.name=FraudShield

# Tells the driver to seamlessly fetch an Entra token from the environment.
spring.datasource.url=jdbc:sqlserver://${DB_SERVER_NAME:fraudshield}.database.windows.net:1433;database=${DB_NAME:fraudshield};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;Authentication=ActiveDirectoryDefault;

# Keep Hibernate configured to automatically generate audit tables
spring.jpa.hibernate.ddl-auto=update

# Explicitly set the dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect